//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegiStar
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourseDetail
    {
        public int courseDetail { get; set; }
        public int courseID { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime finish { get; set; }
    
        public virtual tblCours tblCours { get; set; }
    }
}
