//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegiStar
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrade
    {
        public int gradeID { get; set; }
        public int studentID { get; set; }
        public int courseID { get; set; }
        public int grade { get; set; }
        public string teacherComments { get; set; }
    
        public virtual tblCours tblCours { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
