//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegiStar
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTeacher()
        {
            this.tblCourses = new HashSet<tblCours>();
        }
    
        public int teacherID { get; set; }
        public int userID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime dob { get; set; }
        public System.DateTime joinDate { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public string postalCode { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCours> tblCourses { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
